# Generated by Django 4.2.7 on 2026-05-25 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCreationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_description', models.TextField(blank=True)),
                ('weekly_goal', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('daily_contribution', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('max_members', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_creation_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_group_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('weekly_goal', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('daily_contribution', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('max_members', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_review', 'In Review')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('superadmin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='chamagroup',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='groupadmin',
            name='can_approve_members',
        ),
        migrations.RemoveField(
            model_name='groupadmin',
            name='can_edit_settings',
        ),
        migrations.AddField(
            model_name='chamagroup',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamagroup',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamagroup',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chamagroup',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupadmin',
            name='managed_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='api.chamagroup'),
        ),
        migrations.DeleteModel(
            name='AdminRequest',
        ),
    ]
