# Generated by Django 4.2.7 on 2026-05-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupadmin',
            old_name='assigned_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='groupadmin',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='member',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='member',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_group_admin',
        ),
        migrations.RemoveField(
            model_name='member',
            name='location',
        ),
        migrations.RemoveField(
            model_name='member',
            name='occupation',
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='GroupCreationRequest',
        ),
    ]
